# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?allowMultiQueries=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
  mail:
    host: smtp.newbeiyang.com
    port: 25
    username: smcp@newbeiyang.com
    password: 1234abcd$
    test-field: testField

# 配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.demo.domain

# log日志级别
logging:
  level:
    com:
      example:
        demo:
          mapper: debug

