
# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?allowMultiQueries=true&serverTimezone=UTC&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  mail:
    host: smtp.163.com
    port: 25
    username: username@163.com
    password: password


# 配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.demo.domain
  config-location: classpath:mybatis-config.xml

# log日志级别
logging:
  level:
    com:
      example:
        demo:
          mapper: debug

feign:
  path: '@within(org.springframework.cloud.openfeign.FeignClient)'

server:
  port: 8088
