# 数据库连接
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?allowMultiQueries=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
  mail:
    host: smtp.163.com
    port: 25
    username: username@163.com
    password: password

# 配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.demo.domain

# log日志级别
logging:
  level:
    com:
      example:
        demo:
          mapper: debug
      alibaba:
        nacos:
          client:
            naming:WARN
